services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: codecoach_app
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
      # - "9000:9000"
    depends_on:
      - db
    working_dir: /var/www
    # entrypoint: ["sh", "-c", "./docker-entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: codecoach_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: codecoach
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: codecoach_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
