version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codecoach_app
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: codecoach_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]

  db:
    image: mysql:8.0
    container_name: codecoach_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: codecoach
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: codecoach_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
