version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codecoach_app
    volumes:
      - ./backend:/var/www
      - ./frontend:/frontend
    ports:
      - "8000:8000"
      - "9000:9000"  # PHP-FPM
    depends_on:
      - db
    entrypoint: ["sh", "-c", "./docker-entrypoint.sh"]
    working_dir: /var/www

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codecoach_frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: codecoach_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: codecoach
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: codecoach_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
